--- 
image: "node:6.5.0"
pages: 
  artifacts: 
    paths: 
      - public
  cache: 
    paths: 
      - node_modules/
  only: 
    - master
  script: 
    - "echo \"$RECIPIENTS\" > src/recipients.js"
    - "sed -i -e '/\"name\": \"muna-js\",/a\\'$'\\n'\"\\ \\ \\\"homepage\\\": \\\"$CI_PAGES_URL\\\",\" package.json"
    - "npm install"
    - "CI=false npm run build"
    - "rm -rf public"
    - "mv build public"
  stage: deploy

